DoAnQuanLyTapHoa/Models/UserID.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyTapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserID
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserID()
        {
            this.DonHang = new HashSet<DonHang>();
        }
    
        public int MaUser { get; set; }
        public string TenUser { get; set; }
        public string RoleUser { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHang { get; set; }
    }
}

DoAnQuanLyTapHoa/Controllers/UserIDsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAnQuanLyTapHoa.Models;

namespace DoAnQuanLyTapHoa.Controllers
{
    public class UserIDsController : Controller
    {
        private QuanLyTapHoaFinalEntities1 db = new QuanLyTapHoaFinalEntities1();

        // GET: UserIDs
        public ActionResult Index()
        {
            return View(db.UserID.ToList());
        }

        // GET: UserIDs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserID userID = db.UserID.Find(id);
            if (userID == null)
            {
                return HttpNotFound();
            }
            return View(userID);
        }

        // GET: UserIDs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserIDs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaUser,TenUser,RoleUser,Password")] UserID userID)
        {
            if (ModelState.IsValid)
            {
                db.UserID.Add(userID);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userID);
        }

        // GET: UserIDs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserID userID = db.UserID.Find(id);
            if (userID == null)
            {
                return HttpNotFound();
            }
            return View(userID);
        }

        // POST: UserIDs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaUser,TenUser,RoleUser,Password")] UserID userID)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userID).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userID);
        }

        // GET: UserIDs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserID userID = db.UserID.Find(id);
            if (userID == null)
            {
                return HttpNotFound();
            }
            return View(userID);
        }

        // POST: UserIDs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserID userID = db.UserID.Find(id);
            db.UserID.Remove(userID);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnQuanLyTapHoa/Views/UserIDs/Create.cshtml
@model DoAnQuanLyTapHoa.Models.UserID

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tạo người dùng mới</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaUser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaUser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenUser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenUser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoleUser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoleUser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoleUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DoAnQuanLyTapHoa/Views/UserIDs/Delete.cshtml
@model DoAnQuanLyTapHoa.Models.UserID

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserID</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoleUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoleUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DoAnQuanLyTapHoa/Views/UserIDs/Details.cshtml
@model DoAnQuanLyTapHoa.Models.UserID

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>UserID</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoleUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoleUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaUser }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DoAnQuanLyTapHoa/Views/UserIDs/Edit.cshtml
@model DoAnQuanLyTapHoa.Models.UserID

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<div class="headerOfQuanLy">
    <h2 class="headerTextOfQuanLy">Chỉnh sửa Người dùng</h2>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>UserID</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaUser)

        <div class="form-group">
            @Html.LabelFor(model => model.TenUser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenUser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoleUser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoleUser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoleUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DoAnQuanLyTapHoa/Views/UserIDs/Index.cshtml
@model IEnumerable<DoAnQuanLyTapHoa.Models.UserID>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<div class="headerOfQuanLy">
    <h2 class="headerTextOfQuanLy">Quản lý Người dùng</h2>

    <p class="createNew">
        @Html.ActionLink("Thêm Mới", "Create", "UserIDs", null, new { @class = "createNew btn btn-light" })
    </p>
</div>

<table class="table">
    <tr>
        <th><p>Tài khoản</p></th>
        <th>
            @Html.DisplayNameFor(model => model.TenUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.MaUser)</td>
            <td>
                @Html.DisplayFor(modelItem => item.TenUser)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoleUser)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.MaUser }) |
                @Html.ActionLink("Details", "Details", new { id = item.MaUser }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.MaUser })
            </td>
        </tr>
    }

</table>