DoAnQuanLyTapHoa/Models/LoaiSP.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyTapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiSP()
        {
            this.SanPham = new HashSet<SanPham>();
        }
    
        public string MaLoai { get; set; }
        public string TenLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPham { get; set; }
    }
}

DoAnQuanLyTapHoa/Controllers/LoaiSPsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAnQuanLyTapHoa.Models;

namespace DoAnQuanLyTapHoa.Controllers
{
    public class LoaiSPsController : Controller
    {
        private QuanLyTapHoaFinalEntities1 db = new QuanLyTapHoaFinalEntities1();

        // GET: LoaiSPs
        public ActionResult Index()
        {
            return View(db.LoaiSP.ToList());
        }

        // GET: LoaiSPs/Details/
        public ActionResult Details(string id)
        {            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }            
            LoaiSP loaiSP = db.LoaiSP.Find(id);
            if (loaiSP == null)
            {
                return HttpNotFound();
            }
            return View(loaiSP);
        }

        // GET: LoaiSPs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LoaiSPs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaLoai,TenLoai")] LoaiSP loaiSP)
        {
            if (ModelState.IsValid)
            {                              
                db.LoaiSP.Add(loaiSP);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            return View(loaiSP);
        }

        // GET: LoaiSPs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiSP loaiSP = db.LoaiSP.Find(id);
            if (loaiSP == null)
            {
                return HttpNotFound();
            }
            return View(loaiSP);
        }

        // POST: LoaiSPs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaLoai,TenLoai")] LoaiSP loaiSP)
        {
            if (ModelState.IsValid)
            {
                db.Entry(loaiSP).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(loaiSP);
        }

        // GET: LoaiSPs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiSP loaiSP = db.LoaiSP.Find(id);
            if (loaiSP == null)
            {
                return HttpNotFound();
            }
            return View(loaiSP);
        }

        // POST: LoaiSPs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            LoaiSP loaiSP = db.LoaiSP.Find(id);
            db.LoaiSP.Remove(loaiSP);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnQuanLyTapHoa/Views/LoaiSPs/Create.cshtml
@model DoAnQuanLyTapHoa.Models.LoaiSP

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>LoaiSP</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.MaLoai, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaLoai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaLoai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenLoai, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenLoai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenLoai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
}

DoAnQuanLyTapHoa/Views/LoaiSPs/Delete.cshtml
@model DoAnQuanLyTapHoa.Models.LoaiSP

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<h3>Bạn có muốn xóa loại sản phẩm này không ?</h3>
<div>
    
    
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenLoai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DoAnQuanLyTapHoa/Views/LoaiSPs/Details.cshtml
@model DoAnQuanLyTapHoa.Models.LoaiSP

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>LoaiSP</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenLoai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaLoai }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DoAnQuanLyTapHoa/Views/LoaiSPs/Edit.cshtml
@model DoAnQuanLyTapHoa.Models.LoaiSP

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}


<div class="headerOfQuanLy">
    <h2 class="headerTextOfQuanLy">Chỉnh sửa Loại sản phẩm</h2>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaLoai)

    <div class="form-group">
        @Html.LabelFor(model => model.TenLoai, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenLoai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenLoai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

</div>
}

DoAnQuanLyTapHoa/Views/LoaiSPs/Index.cshtml
@model IEnumerable<DoAnQuanLyTapHoa.Models.LoaiSP>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<div class="headerOfQuanLy">
    <h2 class="headerTextOfQuanLy">Quản lý Danh Mục Loại Sản Phẩm</h2>

    <p class="createNew">
        @Html.ActionLink("Thêm Mới", "Create", "LoaiSPs", null, new { @class = "createNew btn btn-light" })
    </p>
</div>

<table class="table">
    <tr>
        <th>
            <p>Mã Loại </p>
            @*@Html.DisplayNameFor(model => model.MaLoai)*@
        </th>
        <th>
            <p>Tên Loại</p>
            @*@Html.DisplayNameFor(model => model.TenLoai)*@
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaLoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenLoai)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.MaLoai }) |
                @*@Html.ActionLink("Details", "Details", new { id = item.TenLoai }) |*@
                @Html.ActionLink("Delete", "Delete", new { id = item.MaLoai })
            </td>
        </tr>
    }

</table>