DoAnQuanLyTapHoa/Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyTapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDHs = new HashSet<ChiTietDH>();
            this.Vourchers = new HashSet<Vourcher>();
            this.YeuThiches = new HashSet<YeuThich>();
            this.Maus = new HashSet<Mau>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> GiaSp { get; set; }
        public Nullable<int> GiaGiam { get; set; }
        public int SoLuong { get; set; }
        public string Hinh1 { get; set; }
        public string Hinh2 { get; set; }
        public string Hinh3 { get; set; }
        public string Hinh4 { get; set; }
        public string Hinh5 { get; set; }
        public string Mota { get; set; }
        public string Thongso { get; set; }
        public int MaLoai { get; set; }
    
        public virtual PhanLoai PhanLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDH> ChiTietDHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vourcher> Vourchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuThich> YeuThiches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mau> Maus { get; set; }
    }
}

DoAnQuanLyTapHoa/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAnQuanLyTapHoa.Models;
using System.Globalization;

namespace DoAnQuanLyTapHoa.Controllers
{
    public class SanPhamsController : Controller
    {
        public QLBANDTEntities db = new QLBANDTEntities();

        // GET: SanPhams
        public ActionResult Index()
        {
            var sanPhams = db.SanPhams.Include(s => s.PhanLoai);
            return View(sanPhams.ToList());
        }

        // GET: SanPhams/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.MaLoai = new SelectList(db.PhanLoais, "MaLoai", "TenLoai");
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSP,TenSP,HinhSP,MoTaSP,GiaSP,SoLuongSP,MaLoai,MaNSX")] SanPham sanPham,
            HttpPostedFileBase HinhSP)
        {
            if (ModelState.IsValid)
            {

                if (HinhSP != null)
                {
                    //Lấy tên file của hình được up lên
                    var fileName = Path.GetFileName(HinhSP.FileName);
                    //Tạo đường dẫn tới file
                    var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                    //Lưu tên
                    sanPham.Hinh1 = fileName;
                    //Save vào Images Folder
                    HinhSP.SaveAs(path);
                }

                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaLoai = new SelectList(db.PhanLoais, "MaLoai", "TenLoai", sanPham.MaLoai);
            return View(sanPham);
        }

        // GET: SanPhams/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoai = new SelectList(db.PhanLoais, "MaLoai", "TenLoai", sanPham.MaLoai);
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSP,TenSP,HinhSP,MoTaSP,GiaSP,SoLuongSP,MaLoai,MaNSX")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoai = new SelectList(db.PhanLoais, "MaLoai", "TenLoai", sanPham.MaLoai);
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Products
        [HttpGet]
        public ActionResult ProductList(String searchString)
        {
            // Tạo Products và có tham chiếu đến Loại sản phẩm:
            var products = db.SanPhams.Include(p => p.PhanLoai);

            //Tìm kiếm chuỗi truy vấn theo tên sản phẩm, nếu chuỗi truy vấn SearchString khác rỗng, null
            if(!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(s => s.TenSP.Contains(searchString));
            }
            else
            {
                Console.WriteLine("Không tìm thấy sản phẩm nào");
            }    
            return View(products.ToList());

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnQuanLyTapHoa/Views/SanPhams/Create.cshtml
@model DoAnQuanLyTapHoa.Models.SanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HinhSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTaSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTaSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTaSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuongSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLoai, "MaLoai", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoai", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNSX, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaNSX, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNSX, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DoAnQuanLyTapHoa/Views/SanPhams/Delete.cshtml
@model DoAnQuanLyTapHoa.Models.SanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTaSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTaSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaNSX)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNSX)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiSP.TenLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSP.TenLoai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DoAnQuanLyTapHoa/Views/SanPhams/Details.cshtml
@model DoAnQuanLyTapHoa.Models.SanPham

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTaSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTaSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaNSX)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNSX)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiSP.TenLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSP.TenLoai)
        </dd>

        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.MaSP }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
    </dl>
</div>

DoAnQuanLyTapHoa/Views/SanPhams/Index.cshtml
@model IEnumerable<DoAnQuanLyTapHoa.Models.SanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}

<div class="headerOfQuanLy">
    <h2 class="headerTextOfQuanLy">Quản lý Sản Phẩm</h2>

    <p class="createNew">
        @Html.ActionLink("Thêm Mới", "Create", "SanPhams", null, new { @class = "createNew btn btn-light" })
    </p>
</div>


<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.TenSP)*@
            <p>Tên sản phẩm</p>
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.HinhSP)*@
            <p>Hình sản phẩm</p>
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.MoTaSP)*@
            <p>Mô tả</p>
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.GiaSP)*@
            <p>Giá</p>
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.SoLuongSP)*@
            <p>Số lượng</p>
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.MaNSX)*@
            <p>Nhà sản xuất</p>
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.LoaiSP.TenLoai)*@
            Loại 
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenSP)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.HinhSP)*@
                <img src="~/Content/images/@item.HinhSP" width="60" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MoTaSP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaSP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuongSP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaNSX)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LoaiSP.TenLoai)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.MaSP }) |
                @Html.ActionLink("Details", "Details", new { id = item.MaSP }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.MaSP })
            </td>
        </tr>
    }

</table>

DoAnQuanLyTapHoa/Views/SanPhams/ProductList.cshtml
@*@model DoAnQuanLyTapHoa.Models.SanPham*@
@model IEnumerable<DoAnQuanLyTapHoa.Models.SanPham>

@{  
    ViewBag.Title = "ProductList";
    Layout = "~/Views/Shared/GiaoDienKHLayout.cshtml";
}

@* font awsome *@
<script src="https://kit.fontawesome.com/383abdf887.js" crossorigin="anonymous"></script>

<style>
    .headerOfProductList {
        padding: 0 50px;
        display: flex;
    }

    .linestraight {     
        margin-right: 15px;
        height: 50px;
        border: 3px solid red;
    }

    hr {
        width: 1400px;
        border: 2px solid;
        padding: 0 50px;
        margin: 0 auto;
    }


    /*-------------------------------CSS PHAN SLIDER -----------------------------------------------*/
    .slider {
        margin-bottom: 20px;
    }

    .card-pro-img {
        width: 100%;
        height: 280px;
    }

    .card-pro-name, .card-pro-price {
        font-size: 1.25rem;
        font-weight: 700;
        text-align: center;
    }

    /*----------------css rating ngôi sao --------------*/
    .star-wrapper {
        text-align: center;
    }

        .star-wrapper i {
            font-size: 1em;
            color: #F2BE22;
            text-decoration: none;
            transition: all 0.5s;
        }

            .star-wrapper i:hover {
                color: gold;
                transform: scale(1.3);
            }


    /* css nút mua hàng */
    .btn-mua-hang {
        background: radial-gradient(#c31432, #240b36);
        border-radius: 999px;
        box-shadow: #5E5DF0 0 10px 20px -10px;
        box-sizing: border-box;
        cursor: pointer;
        font-family: Inter,Helvetica,"Apple Color Emoji","Segoe UI Emoji",NotoColorEmoji,"Noto Color Emoji","Segoe UI Symbol","Android Emoji",EmojiSymbols,-apple-system,system-ui,"Segoe UI",Roboto,"Helvetica Neue","Noto Sans",sans-serif;
        font-size: 1.0rem;
        font-weight: 600;
        line-height: 24px;
        opacity: 1;
        outline: 0 solid transparent;
        padding: 8px 18px;
        user-select: none;
        -webkit-user-select: none;
        touch-action: manipulation;
        margin: 10px 0px 0px 20%;
        /*width: fit-content;*/
        word-break: break-word;
        border: 0;
    }

        .btn-mua-hang > a{
            text-decoration: none;
            color: #ffffff;
        }

    /* ------------------- css banner -----------------*/
    .banner-product {
        width: 1300px;
        margin: 20px auto;
    }

    /* -------------------css flash sale sản phẩm ---------------*/
    .flash-sale-header {
        margin: 10px 0;
    }

    .flash-sale-hr {
        width: 1000px;
        margin: 10px auto;
        border: 2px solid #ffffff;
        opacity: 100%;
    }

    .flash-sale {
        width: 100%;
        height: 450px;
        background-color: #ED2B2A;
        border: 1px solid #000000;
    }

    .card-flashsale {
        background-color: #ffffff;
        height: 100%;
    }
   
    .card-flashsale-pro-img{
        width: 280px;
        height: 280px;
    }

    .card-flashsale-pro-img:hover {
        box-sizing: border-box;
        box-shadow: 5px 5px 10px 5px #888888;
        transform: scale(1.01, 1.01);
    }

    .card-flashsale-pro-name {
        text-transform: uppercase;
        font-size: 1.25rem;
        font-weight: bold;
    }

    .card-flashsale-pro-price {
        color: red;
        font-size: 1.1rem;
        font-weight: bold;
    }
</style>

@* PHẦN SLIDER *@
<div class="slider">
    <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="500">
                <img height="500" src="~/Content/images/slider1.png" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item" data-bs-interval="500">
                <img height="500" src="~/Content/images/slider3.png" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item" data-bs-interval="500">
                <img height="500" src="~/Content/images/slider2.png" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item" data-bs-interval="500">
                <img height="500" src="~/Content/images/slider3.png" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

<div class="headerOfProductList">
    <div class="linestraight"></div>
    <h2>Tiệm Tạp Hóa </h2>
</div>

<hr />

<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            decimal price = (decimal)item.GiaSp;
            <div class="col-sm-12 col-sm-6 col-md-3 col-lg-3">
                <div class="card-pro">
                    <a href="@Url.Action("Details", "SanPhams", new { id = item.MaSP })">
                        <img class="card-pro-img" src="~/Content/images/@item.Hinh1" />
                    </a>
                    <p class="card-pro-name">@Html.DisplayFor(model => item.TenSP)</p>
                    <p class="card-pro-price">@price.ToString("#,##0").Replace(',', '.') &#8363 </p>
                    <div class="star-wrapper">
                        <i class="fa-solid fa-star"></i>
                        <i class="fa-solid fa-star"></i>
                        <i class="fa-solid fa-star"></i>
                        <i class="fa-solid fa-star"></i>
                        <i class="fa-solid fa-star"></i>
                    </div>
                    @* nút mua hàng nè   *@
                    <button class="btn-mua-hang" role="button"> 
                        <a href="/XemDonHang/TaoDonHang/@item.MaSP " class="btn-default">Thêm vào đơn hàng</a>
                    </button>

                </div>
            </div>
        }
    </div>
</div>

@* PHẦN BANNER QUẢNG CÁO *@
<div class="banner-product">
    <a href="@Url.Action("ProductList", "SanPhams")">
        <picture>
            <source media="(max-width: 767px)" srcset="//theme.hstatic.net/1000288770/1000794542/14/3_banner_htp_1_large.jpg?v=76">
            <img src="~/Content/images/banner2.jpg" alt="banner" width="100%" loading="lazy" />
        </picture>
    </a>
</div>


@* PHẦN FLASH SALE *@
<div class="flash-sale container text-center">
    <div class="flash-sale-header">
        <img src="//theme.hstatic.net/1000288770/1000794542/14/img_home_featured_title.png?v=76" loading="lazy" width="245" height="50">
    </div>

    <hr class="flash-sale-hr" />
    <div class="row">
        @foreach (var item in Model.Take(4))
        {
            decimal price = (decimal)item.GiaSp;
            <div class="col-sm-12 col-sm-6 col-md-3 col-lg-3">
                <div class="card-pro card-flashsale">
                    <a href="@Url.Action("Details", "SanPhams", new { id = item.MaSP })">
                        <img class="card-flashsale-pro-img" src="~/Content/images/@item.Hinh1" />
                    </a>
                    <p class="card-flashsale-pro-name">@Html.DisplayFor(model => item.TenSP)</p>
                    <p class="card-flashsale-pro-price">@price.ToString("###.#00" + "đ")</p>
                </div>
            </div>
        }
    </div>
    <hr class="flash-sale-hr" />
</div>